name: Build 3DS CIA
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        make
    - name: Create CIA
      run: |
        makerom -f cia -o FlaviosMP3Player.cia -elf build/FlaviosMP3Player.elf -target t
    - name: Upload CIA
      uses: actions/upload-artifact@v4
      with:
        name: MP3-Player
        path: FlaviosMP3Player.cia
